cd %~dp0
@ECHO OFF
ECHO Compiling C example 1...
gcc example1.c -Wall -Wextra -std=c11 -o example1
ECHO Compiling C example 2...
gcc example1.c -Wall -Wextra -std=c11 -o example2
ECHO Compiling C example 3...
gcc example1.c -Wall -Wextra -std=c11 -o example3
ECHO Compiling C example 4...
gcc example1.c -Wall -Wextra -std=c11 -o example4
ECHO Compiling C example 5...
gcc example1.c -Wall -Wextra -std=c11 -o example5
ECHO Compiling C example 6...
gcc example1.c -Wall -Wextra -std=c11 -o example6
ECHO Compiling C example 7...
gcc example1.c -Wall -Wextra -std=c11 -o example7
ECHO Compiling C example 8...
gcc example1.c -Wall -Wextra -std=c11 -o example8
PAUSE
